### PR TITLE
Refactor inner data parsing functions.

### PR DESCRIPTION
**Pull request by nr-nd**
The functions for parsing inner vector and/or option data for individual
interventions had a decent amount of boilerplate/similar code. This
commit moves this shared code into functions that each
data-specific function can use on an as-needed basis.

~~**Do not merge yet.**~~

### CODE REVIEW

**Comment by Baguage** [comment]
It may be a good idea to write tests for those functions

**Comment by nr-nd** [comment]
retest this please

**Comment by nr-nd** [comment]
retest this please

**Comment by nr-nd** [comment]
retest this please

**Comment by nr-nd** [comment]
retest this please

**Comment by nr-nd** [comment]
retest this please

**Comment by nr-nd** [comment]
retest this please

**Comment by nr-nd** [comment]
retest this please

**Comment by nr-nd** [comment]
retest this please

**Pull request merged**
